Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\computational-physics-project-yyWSPRtK-py3.10\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\computational-physics-project-yyWSPRtK-py3.10\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\computational-physics-project-yyWSPRtK-py3.10\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\computational-physics-project-yyWSPRtK-py3.10\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\computational-physics-project-yyWSPRtK-py3.10\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\computational-physics-project-yyWSPRtK-py3.10\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import animation
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.animation import PillowWriter
from matplotlib import cm
import numba
from numba import jit, vectorize, cuda
from IPython.display import HTML
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 7[0m
[0;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01manimation[39;00m [38;5;28;01mimport[39;00m PillowWriter
[0;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m cm
[1;32m----> 7[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumba[39;00m
[0;32m      8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnumba[39;00m [38;5;28;01mimport[39;00m jit, vectorize, cuda
[0;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mIPython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdisplay[39;00m [38;5;28;01mimport[39;00m HTML

[1;31mModuleNotFoundError[0m: No module named 'numba'

